#!/bin/sh
echo "script to enable one of the cameras in the device tree"
echo "-1 - single camera (default)"
echo "-2 - dual cameras"
echo "-A - AiStarVision Cameras (OV5645)"
echo "-D - D3 Engineering Cameras (OV5640 - Leopard Imaging module)"
echo "-S - spidev, user space access to SPI devices"
echo "-U - USB_ACM support (for QBOT)"

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
output_file=""
verbose=0
dual=0
camera=0
usb_acm=0
spidev=0

while getopts "v:12ADSU" opt; do
    case "$opt" in
    v)  verbose=1
        ;;
    2) dual=1
	;;
    A) camera=1	#AiStarVision
	;;
    D) camera=2	#D3Engineering
	;;
    S) spidev=1
	;;
    U) usb_acm=1
	;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

echo "verbose=$verbose, camera=$camera, dual=$dual, spidev=$spidev, usb_acm=$usb_acm Leftovers: $@"


if [ $camera = 1 ]
then
	# AiStarVisionCamera, edit the dtsi file to enable the camera
	cd kernel
	cat ../Patches/OV5645-single.patch | patch -p 1
	if [ $dual = 1 ]
	then
		#enable the second camera
		cat ../Patches/OV5645-dual.patch | patch -p 1
	fi
	cd ..
fi

if [ $camera = 2 ]
then
	#D3 Engineering cameras
	# apply all of the patches
	cd kernel
	cat ../Patches/D3Engineering_Patches/* | patch -p 1
	cd ..
fi

if [ $usb_acm = 1 ]
then
	# support for USB serial devices, type ACM 
	# apply all of the patches
	cd kernel
	cat ../Patches/USB_ACM-enable.patch | patch -p 1
	cd ..
fi

if [ $spidev = 1 ]
then
	# support for spidev user mode access to SPI devices
	# apply all of the patches
	cd kernel
	cat ../Patches/spidev-enable.patch | patch -p 1
	cd ..
fi

# End of file
